name: Build and push the latest build to production

on:
  push:
    tags:
      - 'v*'

jobs:
  build_push_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
       
      - run: |
          docker build . -t ${{ secrets.ACR_NAME }}/contoso-website/app:${GITHUB_REF#refs/tags}
          docker push ${{ secrets.ACR_NAME }}/contoso-website/app:${GITHUB_REF#refs/tags}
