name: Build and push the latest build to staging

on:
  push:
    branches: [ main ]

jobs:
  build_push_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}

    #  - name: Build and push staging images
    #    uses: docker/build-push-action@v2.4.0
    #    with:
    #      context: .
    #      tags: contoso-website/app:latest
    #      repository: contoso-website
          
      - run: |
          docker build . -t ${{ secrets.ACR_NAME }}/contoso-website/app:latest
          docker push ${{ secrets.ACR_NAME }}/contoso-website/app:latest

  deploy:
   runs-on: ubuntu-latest
   needs: build_push_image
   steps:
     - uses: actions/checkout@v2

     - name: Install Helm
       uses: Azure/setup-helm@v1
       with:
        version: v3.3.1
                
     - name: Azure Kubernetes set context
       uses: Azure/aks-set-context@v1
       with:
          # Azure credentials, i.e., output of `az ad sp create-for-rbac --sdk-auth`
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         # Resource group name
         resource-group: rg-erd-prod-we-tapp01
         # AKS cluster name
         cluster-name: aks-erd-prod-we-tapp01
         
     - name: Run Helm Deploy
       run: |
           helm upgrade \
             --install \
             --create-namespace \
             --atomic \
             --wait \
             --timeout 11m0s \
             --namespace staging \
             contoso-website \
             ./kubernetes/contoso-website \
             --set image.repository=${{ secrets.ACR_NAME }} \
             --set dns.name=${{ secrets.DNS_NAME }}
             
             
